# -*- coding: utf-8 -*-
"""Data_Collection.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16USH-avaYDoQqfljsPXNtRFtsaxway_P

# **Adapta Brazil MCTI**

---


https://sistema.adaptabrasil.mcti.gov.br/
"""

import geopandas as gpd
from functools import reduce

"""**Risk Index for floods, flash floods and flooding:** Risk of impact of climate change on socio-ecological systems, considering the threat of geo-hydrological disaster from floods, flash floods and inundations, considering geomorphological characteristics, land use, geological characteristics and climatic indices of intense rainfall (total precipitation in 1 day and in 5 days)."""

# Risk Index for floods, flash floods and flooding
flood_risk_index = gpd.read_file("/content/flood_risk_index_2015.geojson")

"""**Firjan Municipal Development Index for employment and income:** The indicator is composed of four indicators: Autonomy, which is the result of the difference between local revenue and administrative structure, divided by net current revenue; Personnel expenses divided by Net Current Revenue; Liquidity, which is the difference between cash and outstanding payments, divided by net current revenue; and Investments divided by Total Revenue. Average of the **historical series from 2013 to 2020**, based on data produced by the Federation of Industries of the state of Rio de Janeiro (Firjan)."""

# Firjan Municipal Development Index for employment and income
firjan_index = gpd.read_file("/content/development_index.geojson")

"""**Gross Domestic Product by urban area:** Indicator composed of the average Gross Domestic Product at current prices (Thousand Reais) between **2010-2019**, divided by the urbanized area of the municipality (2019 reference) - One Thousand Reais per urbanized square kilometer."""

# Gross Domestic Product by urban area
gdp_urban = gpd.read_file("/content/gdp_urban.geojson")

"""**Population with special needs in disaster situations:** The indicator is composed of the average percentage of elderly people aged 60 or over, children up to 5 years old and People with Disabilities (PwD) in the municipal territory. The data are available in SIDRA tables 1378 and 3429, from the 2010 Census."""

# Population with special needs in disaster situations
pop_special_needs = gpd.read_file("/content/population_special_needs.geojson")

"""**Population density in urbanized areas:** Indicator calculated by the ratio between the number of residents in urban areas and the urbanized area calculation. The number of residents was collected in the 2010 Demographic Census (Table 1378) and the second data was calculated according to geospatial data of urbanized areas from the year 2019 (Reges Geográficas 15789), both made available by the Brazilian Institute of Geography and Statistics (IBGE). The area calculation for this last data was performed by municipality, considering a minimum polygon area of ​​0.09 km²."""

# Urban Population density (2010-2019)
urban_pop_density = gpd.read_file("/content/urban_pop_density.geojson")

"""**Young people who have not completed secondary education by the age of 19:** Formal education is considered a way for individuals to acquire knowledge, skills and competencies, and the absence of these can influence an increase in their sensitivity to geohydrological disaster situations. Indicator represents the percentage of young people aged 15 to 19 who have not completed high school, **obtained in the 2010** IBGE census."""

# Young people who have not completed secondary education by the age of 19
young_no_sec_edu = gpd.read_file("/content/edu_19.geojson")

"""**Municipal income appropriated by the poorest 20%:** Indicator calculated by averaging the five best performers in the Atlas of Human Development in Brazil and the percentage of municipal income held by the poorest 20% of the total income of all groups. Index produced by the Atlas of Human Development in Brazil, based on data from the **2010 **IBGE Census."""

# Municipal income appropriated by the poorest 20% (The data was collected in 2010)
income_poorest_20 = gpd.read_file("/content/income_poorest_20.geojson")

"""**Proportion of inadequate or semi-inadequate households:** This indicator is composed of households with the following characteristics: with a bathroom with an inappropriate drain (rudimentary septic tank; ditch; river, lake or sea; others), with a toilet with an inappropriate drain (rudimentary septic tank; ditch; river, lake or sea; others), without a bathroom or toilet, external walls of prepared wood, external walls of coated adobe or non-durable external wall. The value of the indicator is the result of the ratio between the sum of the households in any of the situations mentioned by the total number of households in the municipality, normalized for all municipalities in the country and treatment of outliers using the winsorization technique. Data provided by the **2010** IBGE Demographic Census, SIDRA: Statistical Tables Bank, table 3502."""

# Proportion of inadequate or semi-inadequate households (The dat was collected in 2010)
inadequate_households = gpd.read_file("/content/inadequate_households.geojson")

"""**Housing in a risk environment:** This indicator was prepared by calculating the total number of permanent households in risk areas for each municipality. The normalization of the values ​​considered only the set of municipalities that contained households in risk areas, with the value 0.3 being assigned as the minimum value and 1 as the maximum value. Data from the Statistical Territorial Base of Risk Areas (BATER), generated by IBGE in 2018 in partnership with institutions that produce risk areas, such as CPRM"""

# Housing in a risk environment (2018)
housing_risk_env = gpd.read_file("/content/housing_risk_env.geojson")

# Create a GeoPandaFrame
gdf_list = [flood_risk_index, firjan_index, gdp_urban, pop_special_needs, urban_pop_density,
            young_no_sec_edu, income_poorest_20, inadequate_households, housing_risk_env]

new_col_name = ['flood_risk_score', 'firjan_index_score', 'gdp_urban', 'pr_pop_special_need', 'urban_pop_density', 'pr_young_no_sec_edu', 'income_poorest_20',
                'pr_inadequare_households', 'pr_housing_risk_env']

for i, (gdf, new_name) in enumerate(zip(gdf_list, new_col_name)):
    gdf = gdf.rename(columns={'value': new_name})
    gdf_list[i] = gdf

result = gdf_list[0]

for i, gdf in enumerate(gdf_list[1:]):
    result = result.merge(gdf, on='name', how='inner', suffixes=(None, f'_{i+1}'))

adapta_brazil_dataset = result[['name', 'flood_risk_score', 'firjan_index_score', 'gdp_urban', 'pr_pop_special_need', 'urban_pop_density', 'pr_young_no_sec_edu', 'income_poorest_20',
                'pr_inadequare_households', 'pr_housing_risk_env']]
adapta_brazil_dataset

"""# **The World Bank Datasets (Spatially Aggregated Data)**
Source Link: https://climateknowledgeportal.worldbank.org/download-data#htab-1497

Documentation: https://worldbank.github.io/climateknowledgeportal/README.html#
"""

import requests
import json
import pandas as pd

"""### **Precipitation**"""

# Precipitation Datasets URLs: Climatology, Heatplot, Timeseries, Timeseries-Smooth

# Country-level Dataset
bra_pr_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_annual,monthly,seasonal_1901-1930,1931-1960,1961-1990,1985-2014,1986-2005,1991-2020,1995-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_heatplot_pr_heatplot_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_pr_timeseries_annual,monthly,seasonal_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries-smooth_pr_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json"
]

# City-level Dataset
city_annual_pr_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_annual_1995-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_annual_1991-2020_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_annual_1985-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_annual_1986-2005_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_annual_1961-1990_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_annual_1931-1960_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_annual_1901-1930_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_pr_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries-smooth_pr_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
]

city_monthly_pr_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_monthly_1995-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_monthly_1991-2020_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_monthly_1986-2005_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_monthly_1985-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_monthly_1961-1990_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_monthly_1931-1960_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_monthly_1901-1930_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_heatplot_pr_heatplot_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_pr_timeseries_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json"
]

city_seasonal_pr_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_seasonal_1995-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_seasonal_1991-2020_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_seasonal_1986-2005_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_seasonal_1985-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_seasonal_1961-1990_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_seasonal_1931-1960_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_pr_climatology_seasonal_1901-1930_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_pr_timeseries_seasonal_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json"
]

# Extract Data from URLs

def extract_data(url_list):
  data_list = []
  for url in url_list:
    r = requests.get(url)
    data = r.json()
    data = json.dumps(data, indent=2)
    data_list.append(data)
  return data_list

bra_data = extract_data(bra_pr_url)
city_annual_data = extract_data(city_annual_pr_url)
city_monthly_data = extract_data(city_monthly_pr_url)
city_seasonal_data = extract_data(city_seasonal_pr_url)

# Flattern JSON Data
def clt_pr_flatten_json(json_data):
    flattened_data = []

    for time_scale in ["annual", "monthly", "seasonal"]:
        for period in json_data['data'][time_scale]:
            for country in json_data['data'][time_scale][period]:
                for date, value in json_data['data'][time_scale][period][country].items():
                    flattened_data.append({
                        'time_scale': time_scale,
                        'period': period,
                        'country': country,
                        'date': date,
                        'clt_precipitation': value
                    })

    return flattened_data

# Parse the JSON string
# Climatology Dataset
def clt_create_df(data):
  for ele in data:
    clt_df = json.loads(data)
    clt_df = pd.DataFrame(clt_pr_flatten_json(clt_df))
  return clt_df

clt_create_df(bra_data[0])

# Heatplot Dataset
def hp_pr_df(json_data):
    data = json.loads(json_data)
    data = data['data']['BRA']
    df = pd.DataFrame(list(data.items()), columns=['date', 'heatplot_precipitation'])
    df = df.sort_values('date')
    df['date'] = pd.to_datetime(df['date'], format='%Y-%m')
    return df
hp_pr_df(bra_data[1])

# Time-series Dataset
def ts_pr_df(json_data):
  data = json.loads(json_data)
  annual_data = data['data']['annual']['BRA']
  monthly_data = data['data']['monthly']['BRA']
  seasonal_data = data['data']['seasonal']['BRA']
  a_df = pd.DataFrame.from_dict(annual_data, orient='index', columns=['annual_time_series_precipitation'])
  m_df = pd.DataFrame.from_dict(monthly_data, orient='index', columns=['monthly_time_series_precipitation'])
  s_df = pd.DataFrame.from_dict(seasonal_data, orient='index', columns=['seasonal_time_series_precipitation'])
  a_df.reset_index(inplace=True)
  m_df.reset_index(inplace=True)
  s_df.reset_index(inplace=True)
  a_df.rename(columns={'index': 'date'}, inplace=True)
  m_df.rename(columns={'index': 'date'}, inplace=True)
  s_df.rename(columns={'index': 'date'}, inplace=True)
  return a_df, m_df, s_df

ts_pr_df(bra_data[2])[0]

ts_pr_df(bra_data[2])[1]

ts_pr_df(bra_data[2])[2]

# Time-series Smooth Dataset
def ts_smooth_pr_df(json_data):
    data = json.loads(json_data)
    data = data['data']['BRA']
    df = pd.DataFrame(list(data.items()), columns=['date', 'time_series_smooth_precipitation'])
    df = df.sort_values('date')
    df['date'] = pd.to_datetime(df['date'], format='%Y-%m')
    return df
ts_smooth_pr_df(bra_data[3])

# City-level Climatology Precipitation Datasets
def city_clt_df(json_data):
  data = json.loads(json_data)
  annual_data = data['data']
  df_data = {"subnational":[], "date":[], "annual_precipitation":[]}
  for region, values in annual_data.items():
    df_data["subnational"].append(region)
    for key, value in values.items():
      df_data["date"].append(key)
      df_data['annual_precipitation'].append(value)
  df = pd.DataFrame(df_data)
  return df

pr_city_1995 = city_clt_df(city_annual_data[0])
pr_city_1991 = city_clt_df(city_annual_data[1])
pr_city_1986 = city_clt_df(city_annual_data[2])
pr_city_1985 = city_clt_df(city_annual_data[3])
pr_city_1961 = city_clt_df(city_annual_data[4])
pr_city_1931 = city_clt_df(city_annual_data[5])
pr_city_1901 = city_clt_df(city_annual_data[6])

# City-level Time Series Precipitation Datasets
def ts_pre_city_df(json_data):
  data = json.loads(json_data)
  pre_data = data['data']
  rows = []

  for region, values in pre_data.items():
    for date, value in values.items():
      rows.append({'index': region, 'date': date, 'precipitation': value})
  df = pd.DataFrame(rows)
  df_pivot = df.pivot(index='date', columns='index', values='precipitation')
  df_pivot = df_pivot.reset_index()
  return df_pivot

ts_pre_city_df(city_annual_data[7])





"""### **Average Surface Air Temperature Datasets**"""

# Country-level Datasets
bra_tas_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1995-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1991-2020_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1986-2005_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1985-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1961-1990_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1931-1960_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1901-1930_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1995-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1991-2020_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1986-2005_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1985-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1985-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1961-1990_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1931-1960_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1901-1930_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1995-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1991-2020_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1986-2005_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1985-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1961-1990_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1931-1960_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1901-1930_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_heatplot_tas_heatplot_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tas_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tas_timeseries_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tas_timeseries_seasonal_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json"
]

# City-level Datasets
city_annual_tas_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1995-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1991-2020_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1986-2005_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1985-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1961-1990_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1931-1960_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_annual_1901-1930_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tas_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries-smooth_tas_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json"
]

city_monthly_tas_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1995-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1991-2020_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1986-2005_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1985-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1961-1990_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1931-1960_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_monthly_1901-1930_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tas_timeseries_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json"
]

city_seasonal_tas_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1995-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1991-2020_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1986-2005_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1985-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1961-1990_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1931-1960_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tas_climatology_seasonal_1901-1930_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tas_timeseries_seasonal_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json"
]

"""### **Min Average Air Temperature Datasets**"""

bra_tmin_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1995-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1991-2020_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1986-2005_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1985-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1961-1990_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1931-1960_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1901-1930_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1995-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1991-2020_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1986-2005_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1985-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1961-1990_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1931-1960_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1901-1930_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_heatplot_tasmin_heatplot_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tasmin_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tasmin_timeseries_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tasmin_timeseries_seasonal_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json"
]

# City-level Datasets
bra_tmin_annual_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1995-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1991-2020_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1986-2005_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1985-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1961-1990_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1931-1960_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_annual_1901-1930_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tasmin_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries-smooth_tasmin_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json"
]

bra_tmin_monthly_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1995-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1991-2020_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1986-2005_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1985-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1961-1990_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1931-1960_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_monthly_1901-1930_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_heatplot_tasmin_heatplot_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tasmin_timeseries_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json"
]

bra_tmin_seasonal_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_seasonal_1995-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_seasonal_1991-2020_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_seasonal_1986-2005_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_seasonal_1985-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_seasonal_1961-1990_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_seasonal_1931-1960_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmin_climatology_seasonal_1901-1930_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tasmin_timeseries_seasonal_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json"
]

"""### **Max Average Air Temperature Datasets**"""

bra_tmax_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1995-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1991-2020_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1986-2005_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1985-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1961-1990_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1931-1960_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1901-1930_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1995-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1991-2020_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1986-2005_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1985-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1961-1990_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1931-1960_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1901-1930_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1995-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1991-2020_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1986-2005_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1985-2014_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1961-1990_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1931-1960_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1901-1930_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_heatplot_tasmax_heatplot_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tasmax_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tasmax_timeseries_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tasmax_timeseries_seasonal_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries-smooth_tas_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA?_format=json"
]

# City-level Datasets
bra_tmax_annual_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1995-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1991-2020_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1986-2005_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1985-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1961-1990_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1931-1960_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_annual_1901-1930_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tasmax_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries-smooth_tasmax_timeseries_annual_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json"
]
bra_tmax_monthly_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1995-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1991-2020_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1986-2005_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1985-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1961-1990_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1931-1960_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_monthly_1901-1930_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_heatplot_tasmax_heatplot_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tasmax_timeseries_monthly_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json"
]
bra_tmax_seasonal_url = [
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1995-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1991-2020_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1986-2005_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1985-2014_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1961-1990_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1931-1960_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_climatology_tasmax_climatology_seasonal_1901-1930_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json",
    "https://cckpapi.worldbank.org/cckp/v1/cru-x0.5_timeseries_tasmax_timeseries_seasonal_1901-2022_mean_historical_cru_ts4.07_mean/BRA,BRA.37665,BRA.37666,BRA.37667,BRA.37668,BRA.37669,BRA.37670,BRA.37671,BRA.37672,BRA.37673,BRA.37674,BRA.37675,BRA.37676,BRA.37677,BRA.37694,BRA.37695,BRA.37693,BRA.37692,BRA.37678,BRA.37679,BRA.37680,BRA.37681,BRA.37682,BRA.37683,BRA.37684,BRA.37685,BRA.37686,BRA.37687,BRA.37688,BRA.37689,BRA.37690,BRA.37691?_format=json"
]

